### ISSUE TITLE
Map fonts are not displayed correctry

### ISSUE THREAD

**Issue by inarizushi0309** [matanki-saito/EU4fontcreate#31]
1.30以降マップフォントが正常に動作しなくなった。
1. 1.30.2+main1,2
![20200614194120_1](https://user-images.githubusercontent.com/37979626/84874851-2b9adc00-b0c0-11ea-9aef-a1ab22eab7dc.jpg)
![20200614194118_1](https://user-images.githubusercontent.com/37979626/84874857-2ccc0900-b0c0-11ea-8ebd-ab6e41922b62.jpg)

1. 1.30.2+main1,2+旧フォント（FUNさん提供dds）
![20200617004428_1](https://user-images.githubusercontent.com/37979626/84875049-69980000-b0c0-11ea-8679-62cd87fdc76e.jpg)
![20200617004422_1](https://user-images.githubusercontent.com/37979626/84875051-6b61c380-b0c0-11ea-96fd-c4d2b0ff9e69.jpg)

1. 1.30.2+main1,2+[++ Japanese Map Font: Mincho
](https://steamcommunity.com/sharedfiles/filedetails/?id=2010192304)
![20200617020047_1](https://user-images.githubusercontent.com/37979626/84875252-b085f580-b0c0-11ea-970a-bb6597141601.jpg)

1. 1.29.6(巻き戻し)+main1,2
![20200617144441_1](https://user-images.githubusercontent.com/37979626/84875343-ceebf100-b0c0-11ea-9310-33d74e0c277b.jpg)

**Comment by matanki-saito** [comment]
tgaからddsに変更したことによって解決したのでClose
